apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mjs-app
  template:
    metadata:
      labels:
        app: mjs-app
    spec:
      containers:
      - name: app
        image: maortaieb/k8s-web-hello:latest
        command: ["node", "index.mjs"]
        ports:
        - containerPort: 3000

